version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apartment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ROOT_USERNAME: root
      ROOT_EMAIL: root@example.com
      ROOT_PASSWORD: ChangeMe123!
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: apartment_db
      NODE_ENV: production
    depends_on:
      - postgres
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./uploads:/usr/src/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      # For example, if your Next.js app needs to know where the API is:
      NEXT_PUBLIC_API_URL: http://nginx/api
      NODE_ENV: production
    depends_on:
      - backend
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
